name: Build and Publish Conan Package

on: 
    push:

    workflow_dispatch:
        inputs:
            package_name:
                description: 'Conan package name'
                required: true
                default: '1.0.0'
                type: string
            package_version:
                description: 'Conan package version'
                required: true
                default: 'package' 
                type: string
            package_path:
                description: 'Package path'
                required: true
                default: ''

env:
    PACKAGE_NAME: ${{ inputs.package_name }}
    PACKAGE_VERSION: ${{ inputs.package_version }}
    PACKAGE_PATH: ${{ inputs.package_path }}

jobs:
  get_commit_diff:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    outputs:
      package_path: ${{ steps.export.outputs.PACKAGE_PATH }}
      package_name: ${{ steps.export.outputs.PACKAGE_NAME }}
      package_version: ${{ steps.export.outputs.PACKAGE_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install requests

      - name: Run script to get commit diff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python git_changes_detector.py

      - name: Debug Environment Variables
        run: |
          echo DEBUG: PACKAGE_PATH=%PACKAGE_PATH%
          echo DEBUG: PACKAGE_NAME=%PACKAGE_NAME%
          echo DEBUG: PACKAGE_VERSION=%PACKAGE_VERSION%

      - name: Export package variables
        id: export
        run: |
            echo PACKAGE_PATH=%PACKAGE_PATH: =% >> %GITHUB_OUTPUT%
            echo PACKAGE_NAME=%PACKAGE_NAME: =% >> %GITHUB_OUTPUT%
            echo PACKAGE_VERSION=%PACKAGE_VERSION: =% >> %GITHUB_OUTPUT%
            echo DEBUG: Writing to GITHUB_OUTPUT...
            type %GITHUB_OUTPUT%
        

  use_package_info:
    needs: get_commit_diff
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    env:
        PACKAGE_PATH: "${{ needs.get_commit_diff.outputs.package_path }}"
        PACKAGE_NAME: "${{ needs.get_commit_diff.outputs.package_name }}"
        PACKAGE_VERSION: "${{ needs.get_commit_diff.outputs.package_version }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug Outputs from Previous Job
        run: |
          echo DEBUG: PACKAGE_PATH=%PACKAGE_PATH%
          echo DEBUG: PACKAGE_NAME=%PACKAGE_NAME%
          echo DEBUG: PACKAGE_VERSION=%PACKAGE_VERSION%

      - name: Navigate to PACKAGE_PATH and list contents
        run: |
          if exist %PACKAGE_PATH% (
            cd %PACKAGE_PATH%
            dir
          ) else (
            echo Error: PACKAGE_PATH does not exist!
            exit /b 1
          )
