name: Build and Publish Conan Package

on: 
    push:

jobs:
  detect_package_information:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    outputs:
      changed_files: ${{ steps.detect.outputs.changed_files }}
      diff_content: ${{ steps.detect.outputs.diff_content }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Ensures we have history to compare

      - name: Detect changed files in tools directory
        id: detect
        run: |
          git diff --name-only HEAD^ HEAD > changed_files.txt 2>nul
          if %ERRORLEVEL% NEQ 0 echo No changes detected. > changed_files.txt

          git diff HEAD^ HEAD > diff_content.txt 2>nul
          if %ERRORLEVEL% NEQ 0 echo No changes detected. > diff_content.txt

          echo Changed files:
          type changed_files.txt

          echo Diff content:
          type diff_content.txt

          REM Append each line of changed files to GITHUB_OUTPUT
          echo changed_files= >> %GITHUB_OUTPUT%
          for /F "delims=" %%A in (changed_files.txt) do echo %%A>> %GITHUB_OUTPUT%

          REM Append each line of diff content to GITHUB_OUTPUT
          echo diff_content= >> %GITHUB_OUTPUT%
          for /F "delims=" %%A in (diff_content.txt) do echo %%A>> %GITHUB_OUTPUT%

