name: Build and Publish Conan Package

on: 
    push:

jobs:
  get_commit_diff:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    outputs:
      package_path: ${{ steps.detect.outputs.package_path }}
      package_name: ${{ steps.detect.outputs.package_name }}
      package_version: ${{ steps.detect.outputs.package_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install requests

      - name: Run script to get commit diff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python git_changes_detector.py

      - name: Debug Environment Variables
        run: |
          echo "DEBUG: PACKAGE_PATH=%PACKAGE_PATH%"
          echo "DEBUG: PACKAGE_NAME=%PACKAGE_NAME%"
          echo "DEBUG: PACKAGE_VERSION=%PACKAGE_VERSION%"

      - name: Export package variables
        id: detect
        run: |
          echo "package_path=%PACKAGE_PATH%" >> %GITHUB_OUTPUT%
          echo "package_name=%PACKAGE_NAME%" >> %GITHUB_OUTPUT%
          echo "package_version=%PACKAGE_VERSION%" >> %GITHUB_OUTPUT%
          echo "DEBUG: Writing to GITHUB_OUTPUT..."
          type %GITHUB_OUTPUT%

  use_package_info:
    needs: get_commit_diff
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - name: Debug Outputs from Previous Job
        run: |
          echo "DEBUG: PACKAGE_PATH: ${{ needs.get_commit_diff.outputs.package_path }}"
          echo "DEBUG: PACKAGE_NAME: ${{ needs.get_commit_diff.outputs.package_name }}"
          echo "DEBUG: PACKAGE_VERSION: ${{ needs.get_commit_diff.outputs.package_version }}"

      - name: Navigate to PACKAGE_PATH and list contents
        run: |
          cd "${{ needs.get_commit_diff.outputs.package_path }}"
          dir
