name: Build and Publish Conan Package

on: 
    push:

jobs:
  detect_package_information:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    outputs:
      changed_files: ${{ steps.detect.outputs.changed_files }}
      diff_content: ${{ steps.detect.outputs.diff_content }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures we have history to compare

      - name: Detect changed files
        id: detect
        run: |
            git diff HEAD^ HEAD > changed.files.txt
            git diff --name-only HEAD^ HEAD > changed_contents.txt

            git diff HEAD^ HEAD 
            git diff --name-only HEAD^ HEAD

            git diff 
            git diff --name-only

            type changed.files.txt
            type changed_contents.txt